#!/bin/sh

set -e
fn=$(basename $0)

echo "$fn:Creating /etc/service directory ... ..."
rm -rf /etc/service 2>/dev/null
mkdir /etc/service
echo "$fn:Symlinking services from /etc/services.d to /etc/service"
	ln -sf /etc/services.d/crond /etc/service
	#ln -sf /etc/services.d/rsyslogd /etc/service

unset fn
