#!/usr/bin/env bash

hubid=hwdm
tag=$(grep -o "V=.*" $(pwd)/Dockerfile | tr -d V= | tr -d . | tr -d - | tr -d '[:space:]')
sudo docker build --force-rm --tag "${hubid}/aptest:latest" .
sudo docker run --rm -it "${hubid}/aptest" ls /etc/service
