#!/bin/sh
set -e

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echo "Start the following services under runit supervisor ... ..."
echo "$(ls -l /etc/service)"

exec env - PATH=${PATH} \
runsvdir -P /etc/service 'Log: .............................................................................................................................'
